services:
  backend:
    build:
      context: ./backend
      tags:
      - bearisoa/clarefi-backend:1.2.45
    image: bearisoa/clarefi-backend:latest
    container_name: clarefi-backend
    expose:
    - '8000'
    restart: always
  frontend:
    build:
      context: ./frontend
      tags:
      - bearisoa/clarefi-frontend:1.0.18
      args:
      - VITE_API_URL=/api
    image: bearisoa/clarefi-frontend:latest
    container_name: clarefi-frontend
    ports:
    - 8082:80
    restart: always
