services:
  backend:
    image: bearisoa/clarefi-backend:latest
    networks:
      - default
    container_name: backend
    expose:
      - "8000"
    restart: always

  frontend:
    image: bearisoa/clarefi-frontend:latest
    networks:
      - default
    container_name: frontend
    ports:
      - "80:80"
    restart: always