# multi-stage build
# stage 1 : train the prod model on the github action runner
FROM python:3.12.3-slim as training-stage

COPY --from=ghcr.io/astral-sh/uv:0.10.8 /uv /uvx /bin/

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-cache

COPY . .

RUN source .venv/bin/activate
RUN python launch_data_pipeline.py
RUN python train_prod_model.py
RUN python create_app.py

# stage 2 : copy all inference files/directories in to make a new prod image
FROM python:3.12.3-slim as deployment-stage

COPY --from=ghcr.io/astral-sh/uv:0.10.8 /uv /uvx /bin/
ENV UV_NO_DEV=1

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-cache

COPY --from=training-stage /app .

CMD [ "uv", "run", "gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "src.api.main:app", "--bind", "0.0.0.0:8000" ]