name: Deploy updates (frontend/backend/compose)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - grid_search
    paths:
      - "backend/**"
      - "frontend/**"
      - "docker-compose*"

jobs:
  Building-Images:
    runs-on: ubuntu-latest
    outputs:
      update_server_app: ${{ steps.git-push-update.outputs.to_update }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files in the frontend folder
        id: changed-files-frontend
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: frontend/**
          files_ignore: |
            frontend/README.md

      - name: Get changed files in the backend folder
        id: changed-files-backend
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: backend/**
          files_ignore: |
            backend/config/data_config.yaml
            backend/config/experiment_result.yaml
            backend/config/gridSearch_config.yaml
            backend/data/**
            backend/explorations/**
            backend/src/core/pipeline/**
            backend/README.md

      - name: Get docker-compose file changed
        id: changed-files-compose
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: docker-compose**.yml
          # files_ignore: |

      - name: Login to Docker Hub
        if: steps.changed-files-frontend.outputs.any_changed == 'true' || steps.changed-files-backend.outputs.any_changed == 'true' || steps.changed-files-compose.outputs.any_changed == 'true'
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # updated : frontend only
      - name: Run step if any file(s) in ONLY the frontend folder change
        if: steps.changed-files-frontend.outputs.any_changed == 'true' && steps.changed-files-backend.outputs.any_changed == 'false' && steps.changed-files-compose.outputs.any_changed == 'false'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-frontend.outputs.all_changed_files }}
        run: |
          echo "Updating Frontend image ..."
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          python update_versions.py --commit="$COMMIT_MSG" --part="frontend"
          docker compose build frontend --push

      # updated : backend only
      - name: Run step if any file(s) in ONLY the backend folder change
        if: steps.changed-files-backend.outputs.any_changed == 'true' && steps.changed-files-frontend.outputs.any_changed == 'false' && steps.changed-files-compose.outputs.any_changed == 'false'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-backend.outputs.all_changed_files }}
        run: |
          echo "Updating Backend image ..."
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          python update_versions.py --commit="$COMMIT_MSG" --part="backend"
          docker compose build backend --push

      # updated : both
      - name: Run step if any file(s) in the backend AND frontend folder change
        if: (steps.changed-files-backend.outputs.any_changed == 'true' && steps.changed-files-frontend.outputs.any_changed == 'true') || steps.changed-files-compose.outputs.any_changed == 'true'
        run: |
          echo "Updating Backend && Frontend images ..."
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          python update_versions.py --commit="$COMMIT_MSG"
          docker compose build --push

      # update : docker-compose file
      - name: Github global config
        if: ${{ success() && (steps.changed-files-frontend.outputs.any_changed == 'true' || steps.changed-files-backend.outputs.any_changed == 'true' || steps.changed-files-compose.outputs.any_changed == 'true')}}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Git push docker compose update
        id: git-push-update
        if: ${{ success() && (steps.changed-files-frontend.outputs.any_changed == 'true' || steps.changed-files-backend.outputs.any_changed == 'true' || steps.changed-files-compose.outputs.any_changed == 'true')}}
        run: |
          if [ -n "$(git status --porcelain docker-compose.yml)" ]; then
            git add docker-compose.yml
            git commit -m "new Docker Image version"
            git push

            echo "to_update=1" >> "$GITHUB_OUTPUT"
          else
            echo "No updates pushed"
            echo "to_update=0" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Check if new model on prod
        id: check-new-model-prod
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: backend/config/model_config.yaml
      
      - name: Upload new model to Demo
        id: git-new-model-to-demo
        if: ${{ success() && steps.check-new-model-prod.outputs.any_changed == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: file-to-upload
          path: backend/models/onnx/current_model.onnx
      
      - name: Send signal to run Demo workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner, 
              repo: context.repo.repo,
              workflow_id: 'update_model.yml',
              ref: 'frontend_demo'
            });

  Deploy-on-server:
    runs-on: vm-prod
    needs: Building-Images
    if: ${{ needs.Building-Images.outputs.update_server_app == '1' }}
    steps:
      - name: Deployment script on server
        run: |
          cd $HOME/clarefi
          wget -O docker-compose.yml https://raw.githubusercontent.com/RandrianantenainaBearisoa/clarefi/refs/heads/main/docker-compose.prod.yml
          docker compose pull && docker compose up -d && docker image prune -f
