name: Deploy full app

on:
  workflow_dispatch:

jobs:
  Building-Images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files in the frontend folder
        id: changed-files-frontend
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: frontend/**
          files_ignore: |
            frontend/README.md

      - name: Get changed files in the backend folder
        id: changed-files-backend
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: backend/**
          files_ignore: |
            backend/config/data_config.yaml
            backend/config/experiment_result.yaml
            backend/config/gridSearch_config.yaml
            backend/data/**
            backend/explorations/**
            backend/README.md
        
      - name: Login to Docker Hub
        if: steps.changed-files-frontend.outputs.any_changed == 'true' || steps.changed-files-backend.outputs.any_changed == 'true'
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # updated : frontend only
      - name: Run step if any file(s) in ONLY the frontend folder change
        if: steps.changed-files-frontend.outputs.any_changed == 'true' && steps.changed-files-backend.outputs.any_changed == 'false'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-frontend.outputs.all_changed_files }}
        run: |
          echo "Updating Frontend image ..."
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          python update_versions.py --commit="$COMMIT_MSG" --part="frontend"
          docker compose build frontend --push

      # updated : backend only
      - name: Run step if any file(s) in ONLY the backend folder change
        if: steps.changed-files-backend.outputs.any_changed == 'true' && steps.changed-files-frontend.outputs.any_changed == 'false'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-backend.outputs.all_changed_files }}
        run: |
          echo "Updating Backend image ..."
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          python update_versions.py --commit="$COMMIT_MSG" --part="backend"
          docker compose build backend --push

      # updated : both
      - name: Run step if any file(s) in the backend AND frontend folder change
        if: steps.changed-files-backend.outputs.any_changed == 'true' && steps.changed-files-frontend.outputs.any_changed == 'true'
        run: |
          echo "Updating Backend && Frontend images ..."
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          python update_versions.py --commit="$COMMIT_MSG"
          docker compose build --push
  
  # Deploy-on-server:
  #   runs-on: vm-prod