name: Get commit message

on:
  workflow_dispatch:

jobs:
  Get-Commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print-commit-message
        run: echo "${{ github.event.head_commit.message }}"