name: Update demo model with new model

on:
  workflow_dispatch:
    inputs:
      uploader_run_id:
        description: "Id of the uploader workflow"
        required: true
        type: string

jobs:
  Get-new-model-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout in the demo branch
        uses: actions/checkout@v4
        with:
          ref: 'frontend_demo_dev'
          fetch-depth: 0

      - name: Download new model
        uses: actions/download-artifact@v8
        with:
          name: onnx-version
          run-id: ${{ inputs.uploader_run_id }}
          path: frontend/public/assets/model_artifact/
          github-token: ${{ secrets.GH_TOKEN }}

      - name: Push new model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add frontend/public/assets/model_artifact/current_model.onnx
            git commit -m "feat: new model on prod"
            git push origin frontend_demo_dev
          else
            echo "No changes, no push"
          fi